spring.datasource.url=jdbc:postgresql://localhost:5432/countrydb
spring.datasource.username=postgres
spring.datasource.password=Praveen

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true